#%RAML 0.8
title: gref
version: 1

baseUri: http://github.com/EconomistDigitalSolutions/goberry
documentation:
  -  title: Overview

/:
  get:
    displayName: Root
/version:
  get:
    displayName: Version
/up:
  head:
    displayName: HealthCheck